# These are supported funding model platforms

open_collective: https://opencollective.com/react-spring
BTC (36fuguTPxGCNnYZSRdgdh6Ea94brCAjMbH): https://bitcoin.org
ETH: 0x6E3f79Ea1d0dcedeb33D3fC6c34d2B1f156F2682
